In [173]:
# -*- coding: utf-8 -*-
import numpy as np

class Agent:

    def __init__(self, alpha=0.05, beta=10**(-5), delta=0.99):
        self.A = ['c', 'd']

        self.epsilon = 1
        self.alpha = alpha
        self.beta = beta
        self.delta = delta
        

        self.s_ind = None
        self.s_t = None
        self.a_ind = None
        self.a = None
        self.s_ind1 = None
        self.s_t1 = None

        self.Q = np.random.uniform(size=(2, 4), low=-0.5, high=0.5)


    def get_next_action(self):
        if np.random.random() < 1-self.epsilon:
            self.a_ind = self.Q[:, self.s_ind].argmax()
        else:
            self.a_ind = np.random.randint(2)
        
        self.a = self.A[self.a_ind]


    def updateQ(self, reward, t):  # upateQ
        
        self.Q[self.a_ind, self.s_ind] = (
                1-self.alpha)*self.Q[self.a_ind, self.s_ind] + self.alpha*(reward + self.delta*self.Q[:, self.s_ind1].max())

        self.s_ind = self.s_ind1
        self.epsilon = np.exp(-self.beta*t)

class Env:
    def __init__(self, r_dd=-2, r_cd=-3, r_cc=-1, r_dc=0):
        self.r_dd = r_dd
        self.r_cd = r_cd
        self.r_cc = r_cc
        self.r_dc = r_dc

    def __call__(self, action1, action2):
        if action1+action2 == 'dd':
            return self.r_dd, 0
        elif action1+action2 == 'cd':
            return self.r_cd, 1
        elif action1+action2 == 'cc':
            return self.r_cc, 2
        elif action1+action2 == 'dc':
            return self.r_dc, 3
        else: 
            raise ValueError("Actions should be 'd' or 'c'")
        


In [179]:
agent1 = Agent()
agent2 = Agent()
environment = Env()

agent1.get_next_action()
agent2.get_next_action()

reward1, agent1.s_ind = environment(agent1.a, agent2.a)
reward2, agent2.s_ind = environment(agent1.a, agent2.a)



for t in range(1000000):
    agent1.updateQ(reward1, t)
    agent2.updateQ(reward2, t)

    agent1.get_next_action()
    agent2.get_next_action()

    reward1, agent1.s_ind1 = environment(agent1.a, agent2.a)
    reward2, agent2.s_ind1 = environment(agent2.a, agent1.a)

print(agent1.a+agent2.a)
print(agent1.Q, agent2.Q)


cc
[[-100.184723   -109.60674433 -100.         -108.80998279]
 [-105.22799562 -101.3088878  -100.57746434 -101.33321468]] [[-100.14106092 -109.65096523 -100.0001923  -110.86839843]
 [-104.82241599 -101.36856802 -100.582943   -101.33608918]]
